---
- hosts: control
  tasks:
  - name: 'install python2'
    raw: apt-get -y install python-simplejson
    become: yes
    become_method: "sudo"
  - name: install passlib
    pip:
      name: passlib
    become: yes
    become_method: "sudo" 
