- hosts: cloud
  gather_facts: no
  remote_user: "{{ my_user }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Get updated files from git repository 
      git: repo=https://github.com/TWNUMBER1/RestAPIPractice.git dest=~{{ unix_user }}/apps/RESTAPP

    - name: chown apps to user 
      file:
        path: ~{{ unix_user }}/apps/RESTAPP
        owner: "{{ unix_user }}"
        group: "{{ unix_user }}"
        recurse: yes
        mode: 0700