- hosts: cloud
  gather_facts: no
  remote_user: "{{ my_user }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Install software-properties-common
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - software-properties-common
      become: yes 
      become_method: "sudo"

    - name: ensure ansible repo is added
      apt_repository: repo='ppa:ansible/ansible' state=present

    - name: Install ansible
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - ansible
      become: yes 
      become_method: "sudo"